apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "app.metadataLabels" $ | nindent 4 }}
  name: {{ template "app.name" . }}-flask
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.metadataLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.metadataLabels" $ | nindent 8 }}
    spec:
      containers:
      - name: flask
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
        env:
          - name: REDIS_HOST
            value: {{ template "app.name" . }}-redis-master
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "app.name" . }}-redis
                key: redis-password 
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
