apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-flask 
spec:
  selector:
    {{- include "app.metadataLabels" $ | nindent 4 -}}
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000