version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    #env_file: .env
  redis:
    image: "redis:alpine"
   # volumes:
    #- ./redis.conf:/usr/local/etc/redis/redis.conf
