version: "3.9"
services:
  web:
    build: .
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    volumes:
      - "redis:/data"
    env_file:
      - ".env"
    restart: always

volumes:
  redis: {}