version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PASSWORD: javi00
  redis:
    image: "redis:alpine"
    volumes:
      - "redis:/data"
    command: redis-server --requirepass javi00
    restart: always

volumes:
  redis: {}