replicas: 1
image:
  name: eu.gcr.io/containers-project-304717/flask-kube
  tag: latest

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

ingress:
  enabled: true
  host: helm.keepcoding.35-203-139-35.nip.io

redis:
  cluster:
    enabled: false
  metrics:
    enabled: true
