apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: grafana
spec:
  rules:
  - host: grafana.keepcoding.35-203-139-35.nip.io
  
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
